
CREATE TABLE IF NOT EXISTS DOMICILIOS(ID_DOMICILIO INT AUTO_INCREMENT PRIMARY KEY, CALLE VARCHAR(255),
NUMERO VARCHAR (255),LOCALIDAD VARCHAR (255),PROVINCIA VARCHAR (255));

CREATE TABLE IF NOT EXISTS PACIENTES(ID_PACIENTE INT AUTO_INCREMENT PRIMARY KEY, NOMBRE VARCHAR(255),
APELLIDO VARCHAR (255), DNI VARCHAR (255), FECHA_INGRESO TIMESTAMP WITHOUT TIME ZONE, ID_DOMICILIO INT);

CREATE TABLE IF NOT EXISTS ODONTOLOGOS(ID_ODONTOLOGO INT AUTO_INCREMENT PRIMARY KEY, NOMBRE VARCHAR(255),
APELLIDO VARCHAR (255), MATRICULA INT);

CREATE TABLE IF NOT EXISTS TURNOS(ID_TURNO INT AUTO_INCREMENT PRIMARY KEY, ID_PACIENTE INT, ID_ODONTOLOGO INT,
FECHA_CITA TIMESTAMP WITHOUT TIME ZONE, FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTES(ID_PACIENTE), FOREIGN KEY (ID_ODONTOLOGO) REFERENCES ODONTOLOGOS(ID_ODONTOLOGO));